services:
  web:
    build: .
    ports:
      - "${DOCKER_EXPOSED_PORT:-3000}:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - next-build-cache:/app/.next
    restart: unless-stopped
volumes:
  next-build-cache:
